import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { userStore } from "./store/userStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  const isAuth = userStore.isAuth;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="space-x-4">
          <Link href={'/'}>Home</Link>
          {isAuth ? (
            <>
      <Link href={'/profile'}>Profile</Link>
      {userStore.role === 'admin' && (
      <Link href={'/admin'}>Admin</Link>
      )}

            </>
            
          ):(
<>      <Link href={'/login'}>Login</Link>
      <Link href={'/signup'}>Signup</Link>
</>
          )}


        </div>
        {children}
      </body>
    </html>
  );
}
